Add app open/close test

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -98,6 +98,11 @@ jobs:
         mkdir -p reports
         QT_QPA_PLATFORM=vnc ${{ env.SITE_PKGS }}/shoopdaloop/run_qml_tests.py -o reports/qml_junit_results.xml,junitxml
         echo "QML test results file: $(ls -la reports/qml_junit_results.xml)"
+    
+    - name: App runs and closes gracefully
+      if: success() || failure() # always run even if the previous step fails
+      run: |
+        QT_QPA_PLATFORM=vnc EXPECT_STAY_OPEN=1 WAIT_MS_BEFORE_CLOSE=5000 N_ITERATIONS=10 WAIT_MS_BEFORE_KILL=10000 ./scripts/test_run_app.sh shoopdaloop
 
     - name: Publish Backend Test Report
       uses: mikepenz/action-junit-report@v3
@@ -166,6 +171,11 @@ jobs:
         mkdir -p reports
         QT_QPA_PLATFORM=vnc ${{ env.SITE_PKGS }}/shoopdaloop/run_qml_tests.py -o reports/qml_junit_results.xml,junitxml
         echo "QML test results file: $(ls -la reports/qml_junit_results.xml)"
+    
+    - name: App runs and closes gracefully
+      if: success() || failure() # always run even if the previous step fails
+      run: |
+        QT_QPA_PLATFORM=vnc EXPECT_STAY_OPEN=1 WAIT_MS_BEFORE_CLOSE=5000 N_ITERATIONS=10 WAIT_MS_BEFORE_KILL=10000 ./scripts/test_run_app.sh shoopdaloop
 
     - name: Publish Backend Test Report
       uses: mikepenz/action-junit-report@v3
