Add Python unit test example and Github Action

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -9,7 +9,7 @@ on:
 env:
   BUILD_TYPE: Debug
   BUILD_DEPENDS_ARCH: qt6 qt6-declarative jack2 lv2 lilv boost spdlog fmt shiboken6 python git cmake ninja pkgconf pyside6 python-pip nlohmann-json xorg-xinit xf86-video-dummy xorg-server jack2
-  BUILD_DEPENDS_PYTHON: ctypesgen
+  BUILD_DEPENDS_PYTHON: ctypesgen pytest
   RUN_DEPENDS_PYTHON: playsound resampy mido jsonschema numpy scipy soundfile pyjacklib
   XORG_CONFIG: |
     Section "Monitor"
@@ -85,6 +85,13 @@ jobs:
         ${{github.workspace}}/build/backend/test/test_runner --reporter junit --out reports/backend_junit_results.xml
         echo "Back-end test results file: $(ls -la reports/backend_junit_results.xml)"
     
+    - name: Python tests
+      if: success() || failure() # always run even if the previous step fails
+      run: |
+        mkdir -p reports
+        pytest --junit-xml=reports/python_junit_results.xml
+        echo "Python test results file: $(ls -la reports/python_junit_results.xml)"
+    
     - name: QML tests
       if: success() || failure() # always run even if the previous step fails
       run: |
@@ -92,6 +99,7 @@ jobs:
         X -config /tmp/x_config.conf &
         sleep 0.5
         DISPLAY=:0 ./test/run_qml_tests.py --junit reports/qml_junit_results.xml
+        echo "QML test results file: $(ls -la reports/qml_junit_results.xml)"
 
     - name: Publish Backend Test Report
       uses: mikepenz/action-junit-report@v3
@@ -101,6 +109,15 @@ jobs:
         detailed_summary: true
         include_passed: true
         check_name: 'Backend Test Report'
+    
+    - name: Publish Python Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'reports/python_junit_results.xml'
+        detailed_summary: true
+        include_passed: true
+        check_name: 'Python Test Report'
     
     - name: Publish QML Test Report
       uses: mikepenz/action-junit-report@v3
