WIP

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -38,6 +38,86 @@ jobs:
         name: wheel
         path: dist/${{ env.WHEEL }}
   
+  # Test the built wheel in an Ubuntu environment using PyPi packages
+  test_wheel_ubuntu_pypi:
+    needs: build_whl
+    runs-on: ubuntu-latest
+    container:
+      image: ubuntu:jammy
+      options: --user root --workdir /
+    
+    steps:
+    - name: Retrieve wheel
+      uses: actions/download-artifact@v3
+      with:
+        name: wheel
+        path: ~/wheel
+
+    - name: Prepare system
+      run: |
+        apt-get update
+        apt-get -y install python3 python3-pip python3-pytest python3-venv python3-virtualenv
+
+    - name: Install wheel
+      run: |
+        python3 -m pip install --break-system-packages ~/wheel/*.whl
+        echo "SITE_PKGS=$(python3 -m pip show shoopdaloop | grep "Location:" | sed -r 's/Location: //g')" >> $GITHUB_ENV
+    
+    - name: Back-end tests
+      if: success() || failure() # always run even if the previous step fails
+      run: |
+        mkdir -p reports
+        ${{ env.SITE_PKGS }}/shoopdaloop/test_runner --reporter junit --out reports/backend_junit_results.xml
+        echo "Back-end test results file: $(ls -la reports/backend_junit_results.xml)"
+    
+    - name: Python tests
+      if: success() || failure() # always run even if the previous step fails
+      run: |
+        mkdir -p reports
+        pytest ${{ env.SITE_PKGS }}/shoopdaloop --junit-xml=reports/python_junit_results.xml
+        echo "Python test results file: $(ls -la reports/python_junit_results.xml)"
+    
+    - name: QML tests
+      if: success() || failure() # always run even if the previous step fails
+      run: |
+        mkdir -p reports
+        echo "::warning title=QMLTEST::TODO: QML test step will not fail if any tests fail. Double-check the summary!"
+        QT_QPA_PLATFORM=vnc ${{ env.SITE_PKGS }}/shoopdaloop/run_qml_tests.py -o reports/qml_junit_results.xml,junitxml
+        echo "QML test results file: $(ls -la reports/qml_junit_results.xml)"
+    
+    - name: App runs and closes gracefully
+      if: success() || failure() # always run even if the previous step fails
+      run: |
+        QT_QPA_PLATFORM=vnc EXPECT_STAY_OPEN=1 WAIT_MS_BEFORE_CLOSE=5000 N_ITERATIONS=10 WAIT_MS_BEFORE_KILL=10000 ${{ env.SITE_PKGS }}/shoopdaloop/scripts/test_run_app.sh shoopdaloop
+
+    - name: Publish Backend Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'reports/backend_junit_results.xml'
+        detailed_summary: true
+        include_passed: true
+        check_name: 'backend test (ubuntu pypi)'
+    
+    - name: Publish Python Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'reports/python_junit_results.xml'
+        detailed_summary: true
+        include_passed: true
+        check_name: 'python test (ubuntu pypi)'
+    
+    - name: Publish QML Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'reports/qml_junit_results.xml'
+        detailed_summary: true
+        include_passed: true
+        check_name: 'qml test (ubuntu pypi)'
+
+  
   # # Test the built wheel in an Arch environment with dependencies pre-installed.
   # test_wheel_arch_systempackages:
   #   needs: build_whl
@@ -187,81 +267,4 @@ jobs:
   #       include_passed: true
   #       check_name: 'qml test (ubuntu system)'
 
-  # # Test the built wheel in an Ubuntu environment using PyPi packages
-  # test_wheel_ubuntu_pypi:
-  #   needs: build_whl
-  #   runs-on: ubuntu-latest
-  #   container:
-  #     image: ubuntu:rolling
-  #     options: --user root --workdir /
-    
-  #   steps:
-  #   - name: Retrieve wheel
-  #     uses: actions/download-artifact@v3
-  #     with:
-  #       name: wheel
-  #       path: ~/wheel
-
-  #   - name: Prepare system
-  #     run: |
-  #       apt-get update
-  #       apt-get -y install python3 python3-pip python3-pytest python3-venv python3-virtualenv
-
-  #   - name: Install wheel
-  #     run: |
-  #       python3 -m pip install --break-system-packages ~/wheel/*.whl
-  #       echo "SITE_PKGS=$(python3 -m pip show shoopdaloop | grep "Location:" | sed -r 's/Location: //g')" >> $GITHUB_ENV
-    
-  #   - name: Back-end tests
-  #     if: success() || failure() # always run even if the previous step fails
-  #     run: |
-  #       mkdir -p reports
-  #       ${{ env.SITE_PKGS }}/shoopdaloop/test_runner --reporter junit --out reports/backend_junit_results.xml
-  #       echo "Back-end test results file: $(ls -la reports/backend_junit_results.xml)"
-    
-  #   - name: Python tests
-  #     if: success() || failure() # always run even if the previous step fails
-  #     run: |
-  #       mkdir -p reports
-  #       pytest ${{ env.SITE_PKGS }}/shoopdaloop --junit-xml=reports/python_junit_results.xml
-  #       echo "Python test results file: $(ls -la reports/python_junit_results.xml)"
-    
-  #   - name: QML tests
-  #     if: success() || failure() # always run even if the previous step fails
-  #     run: |
-  #       mkdir -p reports
-  #       echo "::warning title=QMLTEST::TODO: QML test step will not fail if any tests fail. Double-check the summary!"
-  #       QT_QPA_PLATFORM=vnc ${{ env.SITE_PKGS }}/shoopdaloop/run_qml_tests.py -o reports/qml_junit_results.xml,junitxml
-  #       echo "QML test results file: $(ls -la reports/qml_junit_results.xml)"
-    
-  #   - name: App runs and closes gracefully
-  #     if: success() || failure() # always run even if the previous step fails
-  #     run: |
-  #       QT_QPA_PLATFORM=vnc EXPECT_STAY_OPEN=1 WAIT_MS_BEFORE_CLOSE=5000 N_ITERATIONS=10 WAIT_MS_BEFORE_KILL=10000 ${{ env.SITE_PKGS }}/shoopdaloop/scripts/test_run_app.sh shoopdaloop
-
-  #   - name: Publish Backend Test Report
-  #     uses: mikepenz/action-junit-report@v3
-  #     if: success() || failure() # always run even if the previous step fails
-  #     with:
-  #       report_paths: 'reports/backend_junit_results.xml'
-  #       detailed_summary: true
-  #       include_passed: true
-  #       check_name: 'backend test (ubuntu pypi)'
-    
-  #   - name: Publish Python Test Report
-  #     uses: mikepenz/action-junit-report@v3
-  #     if: success() || failure() # always run even if the previous step fails
-  #     with:
-  #       report_paths: 'reports/python_junit_results.xml'
-  #       detailed_summary: true
-  #       include_passed: true
-  #       check_name: 'python test (ubuntu pypi)'
-    
-  #   - name: Publish QML Test Report
-  #     uses: mikepenz/action-junit-report@v3
-  #     if: success() || failure() # always run even if the previous step fails
-  #     with:
-  #       report_paths: 'reports/qml_junit_results.xml'
-  #       detailed_summary: true
-  #       include_passed: true
-  #       check_name: 'qml test (ubuntu pypi)'
+  
