wip

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -81,7 +81,7 @@ jobs:
             build_type: 'Debug'
             cmake_opts: '"ENABLE_COVERAGE" = "On"'
             coverage: true
-        container: [ "sandervocke/shoopdaloop_build_base_debian_bullseye_x86_64:latest" ]
+        container: [ "docker.io/sandervocke/shoopdaloop_build_base_debian_bullseye_x86_64:latest" ]
         container_options: [ "--user root --workdir /" ]
         arch: [ x86_64 ]
         manylinux_arch: [ x86_64 ]
@@ -100,7 +100,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Build
       uses: ./.github/actions/build_toplevel
       with:
@@ -127,44 +127,44 @@ jobs:
             python: python3
             python_pip_args: -m pip
             python_pytest_args: -m pytest
-            container: sandervocke/shoopdaloop_run_base_debian_latest_x86_64:latest
+            container: docker.io/sandervocke/shoopdaloop_run_base_debian_latest_x86_64:latest
             package: wheel_linux_release
           - name: debug_wheel_debian_stable
             python: python3
             python_pip_args: -m pip
             python_pytest_args: -m pytest
-            container: sandervocke/shoopdaloop_run_base_debian_latest_x86_64:latest
+            container: docker.io/sandervocke/shoopdaloop_run_base_debian_latest_x86_64:latest
             package: wheel_linux_debug
           - name: release_deb_ubuntu_latest
             python: python3
             python_pip_args: -m pip
             python_pytest_args: -m pytest
-            container: sandervocke/shoopdaloop_run_base_debian_latest_x86_64:latest
+            container: docker.io/sandervocke/shoopdaloop_run_base_debian_latest_x86_64:latest
             package: package_linux_release_deb
           - name: release_pyinst_ubuntu_latest
             python: python3
             python_pip_args: -m pip
             python_pytest_args: -m pytest
-            container: sandervocke/shoopdaloop_run_base_debian_latest_x86_64:latest
+            container: docker.io/sandervocke/shoopdaloop_run_base_debian_latest_x86_64:latest
             package: pyinstaller_linux_release
           - name: release_pacman_arch
             python: python
             python_pip_args: -m pip
             python_pytest_args: -m pytest
-            container: sandervocke/shoopdaloop_run_base_arch_x86_64:latest
+            container: docker.io/sandervocke/shoopdaloop_run_base_arch_x86_64:latest
             package: package_linux_release_pacman
           - name: release_rpm_fedora
             python: python3
             python_pip_args: -m pip
             python_pytest_args: -m pytest
-            container: sandervocke/shoopdaloop_run_base_fedora_x86_64:latest
+            container: docker.io/sandervocke/shoopdaloop_run_base_fedora_x86_64:latest
             package: package_linux_release_rpm
           - name: coverage_debian_bullseye
             python: python3
             python_shoopdaloop_args: -m coverage run --source=shoopdaloop
             python_pip_args: -m pip
             python_pytest_args: -m coverage run --source=shoopdaloop -m pytest
-            container: sandervocke/shoopdaloop_build_base_debian_bullseye_x86_64:latest
+            container: docker.io/sandervocke/shoopdaloop_build_base_debian_bullseye_x86_64:latest
             package: wheel_linux_coverage
             coverage: true
             run_cmd_prefix: >-
@@ -190,7 +190,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Test
       uses: ./.github/actions/test_toplevel
       with:
@@ -222,7 +222,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        container: [ "sandervocke/shoopdaloop_build_base_debian_bullseye_arm64:latest" ]
+        container: [ "docker.io/sandervocke/shoopdaloop_build_base_debian_bullseye_arm64:latest" ]
         arch: [ arm64 ]
         manylinux_arch: [ aarch64 ]
         kind:
@@ -251,7 +251,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use container shell
       shell: bash
-      run: echo "WRAP_SHELL=run-in-container.sh" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=run-in-container.sh --shell bash" >> $GITHUB_ENV
     - name: Build
       uses: ./.github/actions/build_toplevel
       with:
@@ -273,18 +273,19 @@ jobs:
       matrix:
         container_arch: [ arm64 ]
         kind:
-          - name: release_wheel_debian_bullseye
+          - name: release_wheel_debian_bullseye_arm
             python: python3
             python_pip_args: -m pip
             python_pytest_args: -m pytest
-            container: sandervocke/shoopdaloop_run_base_debian_latest_arm64:latest
+            container: docker.io/sandervocke/shoopdaloop_run_base_debian_latest_arm64:latest
             package: wheel_linux_arm_release
-          - name: release_deb_ubuntu_latest
+          - name: release_deb_ubuntu_latest_arm
             python: python3
             python_pip_args: -m pip
             python_pytest_args: -m pytest
-            container: sandervocke/shoopdaloop_run_base_ubuntu_latest_arm64:latest
+            container: docker.io/sandervocke/shoopdaloop_run_base_ubuntu_latest_arm64:latest
             package: package_linux_arm_release_deb
+            install_with_sudo: 'true'
     runs-on: ubuntu-latest
     needs: build_linux_arm
     #if: false
@@ -300,7 +301,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use container shell
       shell: bash
-      run: echo "WRAP_SHELL=run-in-container.sh" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=run-in-container.sh --shell bash" >> $GITHUB_ENV
     - name: Test
       uses: ./.github/actions/test_toplevel
       with:
@@ -315,6 +316,8 @@ jobs:
         qpa_platform: vnc
         pyinstaller: ${{ matrix.kind.pyinstaller }}
         codecov_token: ${{ secrets.CODECOV_TOKEN }}
+        install_with_sudo: ${{ matrix.kind.install_with_sudo }}
+        do_qml_tests: false # Too slow on ARM emulation
 
 
 
@@ -363,7 +366,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Build
       uses: ./.github/actions/build_toplevel
       with:
@@ -439,7 +442,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Test
       uses: ./.github/actions/test_toplevel
       with:
@@ -516,7 +519,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Build
       uses: ./.github/actions/build_toplevel
       with:
@@ -576,7 +579,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Test
       uses: ./.github/actions/test_toplevel
       with:
@@ -634,7 +637,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Download artifacts
       uses: actions/download-artifact@v4
       with:
