Use sudo on debian ARM container

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -62,7 +62,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Build
       uses: ./.github/actions/build_toplevel
       with:
@@ -151,7 +151,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Test
       uses: ./.github/actions/test_toplevel
       with:
@@ -211,7 +211,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use container shell
       shell: bash
-      run: echo "WRAP_SHELL=run-in-container.sh" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=run-in-container.sh --shell bash" >> $GITHUB_ENV
     - name: Build
       uses: ./.github/actions/build_toplevel
       with:
@@ -244,6 +244,7 @@ jobs:
             python_pytest_args: -m pytest
             container: docker.io/sandervocke/shoopdaloop_run_base_ubuntu_latest_arm64:latest
             package: package_linux_arm_release_deb
+            install_with_sudo: 'true'
     runs-on: ubuntu-latest
     needs: build_linux_arm
     #if: false
@@ -259,7 +260,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use container shell
       shell: bash
-      run: echo "WRAP_SHELL=run-in-container.sh" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=run-in-container.sh --shell bash" >> $GITHUB_ENV
     - name: Test
       uses: ./.github/actions/test_toplevel
       with:
@@ -274,6 +275,7 @@ jobs:
         qpa_platform: vnc
         pyinstaller: ${{ matrix.kind.pyinstaller }}
         codecov_token: ${{ secrets.CODECOV_TOKEN }}
+        install_with_sudo: ${{ matrix.kind.install_with_sudo }}
         do_qml_tests: false # Too slow on ARM emulation
 
 
@@ -320,7 +322,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Build
       uses: ./.github/actions/build_toplevel
       with:
@@ -395,7 +397,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Test
       uses: ./.github/actions/test_toplevel
       with:
@@ -470,7 +472,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Build
       uses: ./.github/actions/build_toplevel
       with:
@@ -529,7 +531,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Test
       uses: ./.github/actions/test_toplevel
       with:
@@ -587,7 +589,7 @@ jobs:
       uses: sandervocke/setup-shell-wrapper@v1
     - name: Use regular shell
       shell: bash
-      run: echo "WRAP_SHELL=bash" >> $GITHUB_ENV
+      run: echo "WRAP_SHELL=bash --noprofile --norc -eo pipefail" >> $GITHUB_ENV
     - name: Download artifacts
       uses: actions/download-artifact@v4
       with:
